version: '2.1'

services:

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    dns_search: .
    networks:
      lite-tms-net:

  lite-tms:
    build:
      context: lite-tms
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9000:9000"
    dns_search: .
    networks:
      lite-tms-net:

networks:
  lite-tms-net:
    driver: bridge
